version: '3.8'

services:
  db:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  recordsservice:
    build:
      context: ./RecordsService
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
